// <auto-generated />
using System;
using Bag_Of_Homebrew_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bag_Of_Homebrew_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260816172237_AddHealthAndCurrency")]
    partial class AddHealthAndCurrency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bag_Of_Homebrew_API.Model.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GmUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GmUserId");

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.HasIndex("VaultId")
                        .IsUnique();

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("Bag_Of_Homebrew_API.Model.CampaignMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("UserId");

                    b.HasIndex("CampaignId", "UserId")
                        .IsUnique();

                    b.ToTable("CampaignMemberships");
                });

            modelBuilder.Entity("Bag_Of_Homebrew_API.Model.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Copper")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CurrentHp")
                        .HasColumnType("integer");

                    b.Property<int>("Electrum")
                        .HasColumnType("integer");

                    b.Property<int>("Gold")
                        .HasColumnType("integer");

                    b.Property<string>("ManualAc")
                        .HasColumnType("text");

                    b.Property<int?>("MaxHp")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PdfSheetUrl")
                        .HasColumnType("text");

                    b.Property<int>("Platinum")
                        .HasColumnType("integer");

                    b.Property<string>("PortraitUrl")
                        .HasColumnType("text");

                    b.Property<int>("Silver")
                        .HasColumnType("integer");

                    b.Property<int?>("TempHp")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Bag_Of_Homebrew_API.Model.EquipmentSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("SlotType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ItemId");

                    b.ToTable("EquipmentSlots");
                });

            modelBuilder.Entity("Bag_Of_Homebrew_API.Model.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HomebrewDescription")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsPlotFlagged")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PropertiesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.Property<Guid?>("VaultId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("VaultId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Bag_Of_Homebrew_API.Model.ItemTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("ToCharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ToUserId", "CampaignId", "Status");

                    b.ToTable("ItemTransfers");
                });

            modelBuilder.Entity("Bag_Of_Homebrew_API.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("GoogleId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Bag_Of_Homebrew_API.Model.Vault", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"UserId\" IS NOT NULL");

                    b.ToTable("Vaults");
                });

            modelBuilder.Entity("Bag_Of_Homebrew_API.Model.Campaign", b =>
                {
                    b.HasOne("Bag_Of_Homebrew_API.Model.User", "GmUser")
                        .WithMany()
                        .HasForeignKey("GmUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bag_Of_Homebrew_API.Model.Vault", "Vault")
                        .WithOne()
                        .HasForeignKey("Bag_Of_Homebrew_API.Model.Campaign", "VaultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GmUser");

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("Bag_Of_Homebrew_API.Model.CampaignMembership", b =>
                {
                    b.HasOne("Bag_Of_Homebrew_API.Model.Campaign", "Campaign")
                        .WithMany("Memberships")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bag_Of_Homebrew_API.Model.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Bag_Of_Homebrew_API.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Character");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bag_Of_Homebrew_API.Model.Character", b =>
                {
                    b.HasOne("Bag_Of_Homebrew_API.Model.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bag_Of_Homebrew_API.Model.EquipmentSlot", b =>
                {
                    b.HasOne("Bag_Of_Homebrew_API.Model.Character", "Character")
                        .WithMany("EquipmentSlots")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bag_Of_Homebrew_API.Model.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Bag_Of_Homebrew_API.Model.Item", b =>
                {
                    b.HasOne("Bag_Of_Homebrew_API.Model.Character", "Character")
                        .WithMany("Items")
                        .HasForeignKey("CharacterId");

                    b.HasOne("Bag_Of_Homebrew_API.Model.Vault", null)
                        .WithMany("Items")
                        .HasForeignKey("VaultId");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Bag_Of_Homebrew_API.Model.ItemTransfer", b =>
                {
                    b.HasOne("Bag_Of_Homebrew_API.Model.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bag_Of_Homebrew_API.Model.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Bag_Of_Homebrew_API.Model.Vault", b =>
                {
                    b.HasOne("Bag_Of_Homebrew_API.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bag_Of_Homebrew_API.Model.Campaign", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Bag_Of_Homebrew_API.Model.Character", b =>
                {
                    b.Navigation("EquipmentSlots");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Bag_Of_Homebrew_API.Model.User", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("Bag_Of_Homebrew_API.Model.Vault", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
